version: '3'

services:
  cronometer_targets_api:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./data.json:/usr/src/app/data.json

networks:
  default:
    external: true
    name: proxynet
